language: c
sudo: required
dist: xenial
os: linux

env:
  global:
    - OPENSSL_BRANCH=OpenSSL_1_1_1-stable
    - BEE2_BRANCH=master
    - PREFIX=/usr/local

matrix:
  include:
  - os: linux
    compiler: gcc

before_script:
  - git clone --depth 1 -b ${OPENSSL_BRANCH} https://github.com/openssl/openssl.git
  - cd openssl
  - mkdir build
  - cd build
  - ../config shared -d --prefix=${PREFIX} --openssldir=${PREFIX}
  - make -j$(nproc) all 
  - sudo make install > build.log 2>&1 || (cat build.log && exit 1)
  - sudo mv ${PREFIX}/openssl.cnf.dist ${PREFIX}/openssl.cnf
  - sudo sed -i '/\[ new\_oids\ ]/i openssl_conf = openssl_init\n[ openssl_init ]\nengines = engine_section\n[ engine_section ]\nbee2evp = bee2evp_section\n[ bee2evp_section ]\nengine_id = bee2evp\ndynamic_path = /usr/local/lib/libbee2evp.so\ndefault_algorithms = ALL' ${PREFIX}/openssl.cnf
  - cd ..
  - cd ..
  - git clone --depth 1 -b ${BEE2_BRANCH} https://github.com/agievich/bee2.git
  - cd bee2
  - mkdir build
  - cd build
  - cmake ..
  - make > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make install > build.log 2>&1 || (cat build.log && exit 1)
  - cd ..
  - cd ..

script:
  - cd bee2evp
  - export LD_LIBRARY_PATH="${PREFIX}/lib:${LD_LIBRARY_PATH:-}"
  - mkdir build
  - cd build
  - cmake .. 
  - make
  - sudo make install > build.log 2>&1 || (cat build.log && exit 1)

language: python
cache: pip

after_script:
  - cd ../test
  - python test_openssl.py
