language: c
os: linux
dist: xenial
sudo: required

env:
  global:
    - OPENSSL_BRANCH=OpenSSL_1_1_1-stable
    - BEE2_BRANCH=master
    - PREFIX=/usr/local
    - CODECOV_TOKEN="14692d3c-1602-496f-8bb4-24797238978d"

branches:
  only:
  - master

matrix:
  include:
  - compiler: gcc

install:
  - sudo apt-get install -y lcov

before_script:
  - cd ..
  - git clone --depth 1 -b ${OPENSSL_BRANCH} https://github.com/openssl/openssl.git
  - cd openssl
  - mkdir build
  - cd build
  - ../config shared -d --prefix=${PREFIX} --openssldir=${PREFIX}
  - make -j$(nproc) all 
  - sudo make install > build.log 2>&1 || (cat build.log && exit 1)
  - sudo mv ${PREFIX}/openssl.cnf.dist ${PREFIX}/openssl.cnf
  - sudo sed -i '/\[ new\_oids\ ]/i openssl_conf = openssl_init\n[ openssl_init ]\nengines = engine_section\n[ engine_section ]\nbee2evp = bee2evp_section\n[ bee2evp_section ]\nengine_id = bee2evp\ndynamic_path = /usr/local/lib/libbee2evp.so\ndefault_algorithms = ALL' ${PREFIX}/openssl.cnf
  - cd ..
  - cd ..
  - git clone --depth 1 -b ${BEE2_BRANCH} https://github.com/agievich/bee2.git
  - cd bee2
  - mkdir build
  - cd build
  - cmake ..
  - make > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make install > build.log 2>&1 || (cat build.log && exit 1)
  - cd ..
  - cd ..

script:
  - cd bee2evp
  - export LD_LIBRARY_PATH="${PREFIX}/lib:${LD_LIBRARY_PATH:-}"
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Coverage .. 
  - make
  - sudo make install > build.log 2>&1 || (cat build.log && exit 1)
  - cp -a ../test/. .
  - lcov -c -i -d . -o coverage_base.info
  - python test.py
  - lcov -c -d . -o coverage_test.info
  - lcov -a coverage_base.info -a coverage_test.info -o coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info
