name: Build And Test

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  # Запуск только при публиковании нового релиза

jobs:
  build_and_test:
    # Первую джобу смело можем копипастить из экшена для тестирования
    runs-on: [ubuntu-latest]
    steps:
        # Чекаутим код
      - uses: actions/checkout@master
      - name: Install req
        run: sudo apt-get install gcc cmake python3 python
      - name: Run build
        run: |
          cd doc
          bash build.sh
      - name: Check
        run : |
          pwd
          which openssl
          echo $HOME
          ls -al
          cd ./build/local
          ls -al
      - name: Run test
        run: |
          export LD_LIBRARY_PATH="./build/local/lib:${LD_LIBRARY_PATH:-}"
          sudo ldconfig
          python3 ./test/test.py
      - name: Logs
        run: |
          cat ~/s_log.txt
          cat ~/c_log.txt