name: Build And Test

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@master
      - name: Install req
        run: sudo apt-get install gcc cmake python3 python ca-certificates ufw netcat -y
      - name: Run build
        run: |
          cd doc
          bash build.sh
      - name: Check
        run: |
          pwd
          which openssl
          echo $HOME
          ls -al
          cd ./build/local
          ls -al
      - name: Run test
        run: |
          export LD_LIBRARY_PATH="/home/runner/work/bee2evp/bee2evp/build/local/lib:${LD_LIBRARY_PATH:-}"
          export SHELL=/bin/sh
          python3 ./test/test.py
      - name: Cat
        if: ${{ failure() }}
        run: |
          cat s_log.txt
          cat c_log.txt
          ping -c 4 127.0.0.1