name: Build And Test

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: [ubuntu-latest]
    steps:
        # Чекаутим код
      - uses: actions/checkout@master
      - name: Install req
        run: sudo apt-get install gcc cmake python3 python
      - name: Run build
        run: |
          cd doc
          bash build.sh
      - name: Check
        run: |
          pwd
          which openssl
          echo $HOME
          ls -al
          cd ./build/local
          ls -al
      - name: Run test
        run: |
          export LD_LIBRARY_PATH="/home/runner/work/bee2evp/bee2evp/build/local/lib:${LD_LIBRARY_PATH:-}"
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl genpkey -algorithm bign -pkeyopt params:bign-curve256v1 -out priv256.key
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl req -x509 -subj "/CN=www.example.org/O=BCrypto/C=BY/ST=MINSK" -new -key priv256.key -nodes -out cert.pem
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl s_server -key priv256.key -cert cert.pem -tls1_2 -state > /tmp/out.txt &
          sleep 3
          export LD_LIBRARY_PATH="/home/runner/work/bee2evp/bee2evp/build/local/lib:${LD_LIBRARY_PATH:-}"
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl s_client -cipher DHE-BIGN-WITH-BELT-DWP-HBELT -tls1_2 -showcerts -state; cat /tmp/out.txt