name: Build And Test

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: [ubuntu-latest]
    steps:
        # Чекаутим код
      - uses: actions/checkout@master
      - name: Install req
        run: sudo apt-get install gcc cmake python3 python ca-certificates
      - name: Run build
        run: |
          cd doc
          bash build.sh
      - name: Check
        run: |
          pwd
          which openssl
          echo $HOME
          ls -al
          cd ./build/local
          ls -al
      - name: Run test
        run: |
          export LD_LIBRARY_PATH="/home/runner/work/bee2evp/bee2evp/build/local/lib:${LD_LIBRARY_PATH:-}"
          export SHELL=/bin/sh
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl genpkey -algorithm bign -pkeyopt params:bign-curve256v1 -out priv256.key
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl req -days 365 -x509 -subj "/CN=www.example.org/O=BCrypto/C=BY/ST=MINSK" -new -key priv256.key -nodes -out cert.pem
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl s_server -key priv256.key -cert cert.pem -tls1_2 -state > $HOME/out.txt -4 &
          sleep 3
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl s_client -cipher DHE-BIGN-WITH-BELT-CTR-MAC-HBELT -tls1_2 -nbio -showcerts -state
      - name: Cat
        if: ${{ failure() }}
        run: |
          export LD_LIBRARY_PATH="/home/runner/work/bee2evp/bee2evp/build/local/lib:${LD_LIBRARY_PATH:-}"
          export SHELL=/bin/sh
          cat $HOME/out.txt
          cat /home/runner/work/bee2evp/bee2evp/cert.pem | /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl x509 -noout -enddate
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl ciphers
          /home/runner/work/bee2evp/bee2evp/build/local/bin/openssl engine -c -t bee2evp